# Generated by Django 4.1.7 on 2023-03-21 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_name', models.CharField(max_length=200)),
                ('D_cost', models.IntegerField(default=0)),
                ('D_discription', models.CharField(max_length=200)),
                ('x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.category')),
            ],
        ),
    ]
