# Generated by Django 4.1.7 on 2023-03-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default=0, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
