# Generated by Django 4.1.7 on 2023-03-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_image_destination_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='images1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('I_images1', models.ImageField(default=0, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='images2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('I_images2', models.ImageField(default=0, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='images3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('I_images3', models.ImageField(default=0, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='image',
        ),
    ]
