# Generated by Django 4.1.7 on 2023-04-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_images1_images2_images3_delete_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='images2',
        ),
        migrations.DeleteModel(
            name='images3',
        ),
        migrations.AddField(
            model_name='images1',
            name='I_images2',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='images1',
            name='I_images3',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
